spring.config.activate.on-profile: dev

server:
    port: 8080

spring:
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                default_batch_fetch_size: 100
                format_sql: true
                show_sql: true

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3308/gcvd-database?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&autoReconnect=true
        username: root
        password: 1234

---
spring.config.activate.on-profile: prod

server:
    port: 8080

spring:
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: false
        properties:
            hibernate:
                default_batch_fetch_size: 100
                format_sql: false
                show_sql: false

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&autoReconnect=true
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
