name: Auto labeler

on:
  pull_request:
    types: [ opened, edited ]
  issues:
    types: [ opened, edited ]

jobs:
  main:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name : Auto labeling
        uses: hoho4190/issue-pr-labeler@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file-name: labeler-config.yml
